import { Geist, Geist_Mono } from "next/font/google";
import { Yomogi } from 'next/font/google';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Google Fontsから「Yomogi」フォントを取得
const yomogi = Yomogi({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      {/* yomogi.className を body に指定することで、アプリ全体が手書きフォントになります */}
      <body className={yomogi.className}>{children}</body>
    </html>
  );
}
